version: '3.8'

services:
  baseapi:
    build: .
    command: uvicorn app.app:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    expose:
      - '80'
    volumes:
      - .:/app
    env_file:
      - .env
    # networks:
    #   - app-network
    # environment:
    #   - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@127.0.0.1:3306/${MYSQL_DATABASE}
    #   - REDIS_URL=redis://127.0.0.1:6379/0


  # celery_worker:
  #   build: .
  #   command: celery -A core.celery_app worker --loglevel=info
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env
  #   depends_on:
  #     - baseapi_api
  #   networks:
  #     - app-network
  #   environment:
  #     - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@127.0.0.1:3306/${MYSQL_DATABASE}
  #     - REDIS_URL=redis://127.0.0.1:6379/0

  # celery_beat:
  #   build: .
  #   command: celery -A core.celery_app beat --loglevel=info
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env
  #   depends_on:
  #     - baseapi_api
  #   networks:
  #     - app-network
  #   environment:
  #     - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@127.0.0.1:3306/${MYSQL_DATABASE}
  #     - REDIS_URL=redis://127.0.0.1:6379/0

  # flower:
  #   build: .
  #   command: celery -A core.celery_app flower --port=5555
  #   ports:
  #     - "127.0.0.1:5555:5555"
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env
  #   depends_on:
  #     - baseapi_api
  #     - celery_worker
  #   networks:
  #     - app-network
  #   environment:
  #     - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@127.0.0.1:3306/${MYSQL_DATABASE}
  #     - REDIS_URL=redis://127.0.0.1:6379/0


# networks:
#   app-network:
#     driver: bridge 